### ISSUE TITLE
Create minimal Docker dev environment image

### ISSUE THREAD

**Issue by tompaana** [sachinkundu/akstf#26]
The utility scripts using Azure CLI are written in bash, which may often require additional hurdles in Windows. For example, Git Bash will not work with default Azure CLI configuration, and not all users opt for WSL (which itself may not work out-of-the-box). Hence, <strike>it makes sense to provide the scripts also in PowerShell.</strike>it makes sense to create a Docker image for setup environment.

**Comment by sachinkundu** [comment]
Good point. Especially considering that many of the people using this would be windows users. How about we make a docker container with all dependencies baked in? That will prevent toolchain installation completely and we don't have to then maintain two versions of essentially same commands. Docker on windows have improves substantially so that should be ok.
